### ISSUE TITLE
Unable to run example caused by 'status' missing from api response

### ISSUE THREAD

**Issue by Apollo-Roboto** [happydev-ca/evduty-api#4]
I am getting an error when running the example code. it seems like the api response is missing this `status` field. 

```console
$ python ./evtest.py
Traceback (most recent call last):

 ...

  File "C:\Users\Apollo\Temp\evtest.py", line 11, in run
    stations = await api.async_get_stations()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Apollo\AppData\Local\Programs\Python\Python313\Lib\site-packages\evdutyapi\evduty_api.py", line 61, in async_get_stations
    stations = [StationResponse.from_json(s) for s in json_stations]
                ~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "C:\Users\Apollo\AppData\Local\Programs\Python\Python313\Lib\site-packages\evdutyapi\api_response\station_response.py", line 19, in from_json
    status=ChargingStatus(data['status']),
                          ~~~~^^^^^^^^^^
KeyError: 'status'
```

The api does returns 200 with the following payload

```json
[
    {
        "name": "...",
        "address": {
            "street": "...",
            "city": "...",
            "postalCode": "...",
            "formattedAddress": "...",
            "state": "...",
            "taxState": "..."
        },
        "ownerId": "...",
        "latitude": 0.0,
        "longitude": 0.0,
        "initialLatitude": 0.0,
        "initialLongitude": 0.0,
        "id": "...",
        "isRoot": true,
        "isOwner": true,
        "isPartialOwner": false,
        "terminals": [],
        "hours": []
    }
]
```

My car was plugged in when making this request, I would have expected to find `"status": "inUse"` within this payload.

I found this payload from the async_get_stations method in the EVDutyApi class

```diff
    async def async_get_stations(self) -> List[Station]:
        await self.async_authenticate()
        async with self.session.get(f'{self.base_url}/v1/account/stations', headers=self.headers) as response:
+           print(response.status)
+           print(await response.json())
            await self._log("async_get_stations", response)
            await self._raise_on_get_error(response)
            json_stations = await response.json()
            stations = [StationResponse.from_json(s) for s in json_stations]
            await self._async_get_terminals(stations)
            await self._async_get_sessions(stations)
            return stations
```

**Comment by francoisperron** [comment]
The `station.status` field is a summary of the terminals statuses.

In your log, it seems like there's no charging terminals for this station.
`"terminals": []`

I will remove the `station.status` field since it can be computed from terminals statuses.

**Comment by francoisperron** [comment]
Field removed in commit
https://github.com/happydev-ca/evduty-api/commit/27b6b0dcb0a1e470c9c311de2464bdfb80f9f7d2
